### ISSUE TITLE
Dataset format?

### ISSUE THREAD

**Issue by violetteavi** [MIT-SPARK/Kimera-VIO-Evaluation#5]
What format does this package expect the datasets to come in? Will it work with rosbags?

**Comment by ToniRV** [comment]
This package is deprecated unfortunately, checkout https://github.com/ToniRV/Kimera-VIO-Evaluation

Answering your question: rosbags per-se are not supported, but they could be, if they were parsed correctly.

The way this repo is organized is such that if you have a folder with a traj_gt.csv and a traj_vio.csv it will compute the errors between ground-truth and estimated trajectories.

We use evo https://github.com/MichaelGrupp/evo as backend for this type of evaluation.

**Comment by ToniRV** [comment]
BTW, it seems https://github.com/MichaelGrupp/evo now supports rosbags as well, so it seems the heavy lift is already done.

It would be a matter of updating our dependency to evo (now we depend on a fork of mine evo-1, which I would prefer to get rid of tbh).

**Comment by violetteavi** [comment]
Ok! Can we change the README to show this is deprecated and have a link to the up-to-date version?

**Comment by violetteavi** [comment]
Marked the repo as deprecated in the README-- messed up and pushed to the master branch instead of the branch I planned to PR. I think it's ok though, as this is a minor change to a text file.
